services:
  app:
    build: .
    container_name: pozitivne_spravy_app
    restart: always
    ports:
      - "5001:5001"
    # Načítanie premenných z .env súboru
    env_file:
      - .env
    volumes:
      - ./clanky.db:/app/clanky.db
      - ./spracovanie.log:/app/spracovanie.log
      - ./static/podcast_pozitivny.mp3:/app/static/podcast_pozitivny.mp3
      - ./static/podcast_vsetky.mp3:/app/static/podcast_vsetky.mp3
    command: gunicorn --bind 0.0.0.0:5001 app:app

  scheduler:
    build: .
    container_name: pozitivne_spravy_scheduler
    restart: always
    # Aj scheduler potrebuje API kľúč
    env_file:
      - .env
    volumes:
      - ./clanky.db:/app/clanky.db
      - ./spracovanie.log:/app/spracovanie.log
      - ./static:/app/static
    # Spustí cron v popredí
    command: cron -f
